"""profile: split name fields, add amazon_site + other_accounts, drop old fields

Revision ID: 4428b24bcff6
Revises: 8b34e0cefc8c
Create Date: 2025-10-15 12:37:48.832727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4428b24bcff6'
down_revision = '8b34e0cefc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('amazon_site', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('other_accounts', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
        batch_op.drop_column('phone')
        batch_op.drop_column('timezone')
        batch_op.drop_column('full_name')
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('other_accounts')
        batch_op.drop_column('amazon_site')
        batch_op.drop_column('job_title')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
