"""Creation of user_sites and modification of user_profile

Revision ID: 5c2130867675
Revises: 2d9977fa3cfb
Create Date: 2025-10-30 16:02:09.780036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2130867675'
down_revision = '2d9977fa3cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sites_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('amazon_site')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amazon_site', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sites_user_id'))

    op.drop_table('user_sites')
    # ### end Alembic commands ###
