"""users: add email_verified_at and profile_completed_at

Revision ID: e4a7c931671c
Revises: 2cfc97fac1ff
Create Date: 2025-10-16 18:32:25.470588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a7c931671c'
down_revision = '2cfc97fac1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('profile_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_completed_at')
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###
